[Feat] #77 infinite scroll 구현
YAPP-Github/Coffice-iOS pull request #117
Opened 2023-07-08 16:36 UTC by NewHooon

## ☕️ PR 요약

- [ ] 무한스크롤 구현
- [ ] 카페 카드뷰 레이아웃 수정

## 📸 ScreenShot

![Simulator Screen Recording - iPhone 13 Pro Max - 2023-07-09 at 01 32 08](https://github.com/YAPP-Github/Coffice-iOS/assets/108966759/0341f6c6-acf8-4b1b-aec9-73363a198a17)

#### Linked Issue

close #77

2023-07-08 17:03 UTC, applebuddy requested changes
수고하셨습니다. 
의견 확인 부탁드립니다. (제 리뷰도 확인 부탁드려요. 🙏🏻)

2023-07-08 17:03 UTC, applebuddy commented on Projects/Coffice/Sources/App/Main/Search/CafeSearchListCore.swift
> +          return .send(.scrollAndRequestSearchPlace(state.lastCafeDistance))
P2: 여기 그냥 EffectTask로 반환하면 문제가 되나요?

2023-07-08 17:03 UTC, applebuddy commented on Projects/Coffice/Sources/App/Main/Search/CafeSearchListView.swift
> +                }
P2: 들여쓰기 확인해주세요.

2023-07-08 17:03 UTC, applebuddy commented on Projects/Coffice/Sources/App/Main/Search/CafeSearchListView.swift
> +                }
P2: cafeList element가 Identifiable을 준수할 수 있다면, index기반이 아닌 element 단위로 처리를 할 수 있을 것 같은데 그게 가능한지 고민해보면 좋을 것 같습니다. (index 기반으로 구성해야만하는 로직이라면 어쩔 수 없겠지만...)

2023-07-09 03:58 UTC, NewHooon commented on Projects/Coffice/Sources/App/Main/Search/CafeSearchListCore.swift
> +          return .send(.scrollAndRequestSearchPlace(state.lastCafeDistance))
사실 두 방식 모두 동작은 할 것 같습니다만, 구체적인 성능 이슈나 디테일한 부분에 대해서는 파악하지 못한 것 같습니다..!
[.send ]방식의 경우, child-parent Communication에 한해서 제한적으로 사용하길 권장하는 것 같습니다
[EffectTask]방식의 경우, the outside World로  제시하고 있네요~ 
지금 상황에서는 CafeSearchListCore[child]가 CafeMapCore[parent]와 Communication하는 상황이라고 생각합니다.
맥락상 .send 가 적합해보이는데 의견 부탁드립니다~!

<img width="300" alt="스크린샷 2023-07-09 12 49 47" src="https://github.com/YAPP-Github/Coffice-iOS/assets/108966759/020ed380-95e7-4398-9c07-d19ed3706c32">
<br></br>
<img width="308" alt="image" src="https://github.com/YAPP-Github/Coffice-iOS/assets/108966759/7926d90a-922b-490d-9345-d62b3a69fbcb">

2023-07-09 03:58 UTC, NewHooon commented on Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
> +                 !state.cafeSearchListState.cafeList.contains($0)
넵 확인하겠습니다~

2023-07-09 03:58 UTC, NewHooon commented on Projects/Coffice/Sources/App/Main/Search/CafeCardView.swift
> +          .frame(maxWidth: screendWidth - 48, alignment: .leading)
반영하겠습니다~

2023-07-09 03:59 UTC, NewHooon commented on Projects/Coffice/Sources/App/Main/Search/CafeSearchListView.swift
> +                }
한번 수정해보겠습니다~

2023-07-09 04:01 UTC, NewHooon commented on Projects/Coffice/Sources/App/Main/Search/CafeMapView.swift
>          .applyCofficeFont(font: .subtitle1Medium)
참고하겠습니다~!!

2023-07-09 05:59 UTC, Neph3779 commented on Projects/Coffice/Sources/App/Main/Search/CafeSearchListCore.swift
> +          return .send(.scrollAndRequestSearchPlace(state.lastCafeDistance))
@NewHooon 대괄호에 의미가 없고 단순 강조용의 사용이라면 
단어를 `로 감싸는 마크다운 문법으로 바꿔주시는게 보기에 더 편할 것 같습니다~
ex) `.send`의 경우

2023-07-09 06:02 UTC, NewHooon commented on Projects/Coffice/Sources/App/Main/Search/CafeSearchListCore.swift
> +          return .send(.scrollAndRequestSearchPlace(state.lastCafeDistance))
오오..! 맞아요~ 강조의미였습니다ㅎㅎ
참고하겠습니다~~

2023-07-09 06:38 UTC, applebuddy commented on Projects/Coffice/Sources/App/Main/Search/CafeSearchListCore.swift
> +          return .send(.scrollAndRequestSearchPlace(state.lastCafeDistance))
@NewHooon 의도하신게 맞고, 동작이 문제없다면, 이부분은 의논된적은 없어서 그대로 사용하시고, 다음에 얘기 나눠보면 좋겠습니다!

2023-07-09 07:41 UTC, applebuddy submitted a review, later dismissed
수고하셨습니다. 
추가로 리뷰 남겨두었으니, 의견 확인부탁드립니다.

2023-07-09 07:41 UTC, applebuddy commented on Projects/Coffice/Sources/App/Main/Search/CafeCardView.swift
> +            maxWidth: viewStore.maxScreenWidth - 48,
P2: -48 이라는 연산도 maxScreenWidth에서 담당하면 좋지 않을까 생각이 들긴 하네요. maxWidth 라는 이름 자체가 -48을 포함하고 있지 않나 싶어서요.

2023-07-09 07:41 UTC, applebuddy commented on Projects/Coffice/Sources/App/Main/Search/CafeCardView.swift
> +                  height: (viewStore.maxScreenWidth - 56) / 3
P2: maxScreenWidth를 Reducer에서 관리하게 되어서 여기 연산 결과 자체를 계산프로퍼티방식으로 해서 나오게 할 수도 있겠네요.

2023-07-09 07:41 UTC, applebuddy commented on Projects/Coffice/Sources/App/Main/Search/CafeSearchListView.swift
> +                  .onTapGesture {}
P2: Cafe 모델이 Identifiable을 준수하도록 하면 id 명시를 안해도 될 것 같은데 그냥 id 필드만 추가했네요. 이게 어떤이유로 더 좋다고 판단하신건가요?

2023-07-09 07:44 UTC, NewHooon commented on Projects/Coffice/Sources/App/Main/Search/CafeCardView.swift
> +            maxWidth: viewStore.maxScreenWidth - 48,
넵 지금 geomertyReader로 받는 방식이 리베이스 후에, Invalid frame dimesions 문제가 발생하여, 해결해보겠습니다

2023-07-09 07:49 UTC, NewHooon commented on Projects/Coffice/Sources/App/Main/Search/CafeSearchListView.swift
> +                  .onTapGesture {}
개인적으로 Identifiable 프로토콜 채택 시, Cafe 모델에 `let id:UUID`와 같은 프로퍼티를 추가해야 하는데, 
이미 Cafe 모델에 있는 `placeId` 프로퍼티가 고유 식별자 역할을 하고 있기 때문에 해당 값을 적용하였습니다.

2023-07-09 11:45 UTC, applebuddy approved these changes
하나 더 보이는게 있어서 의견드렸어요~

2023-07-09 11:45 UTC, applebuddy commented on Projects/Coffice/Sources/App/Main/Search/CafeCardView.swift
> +              Image(uiImage: CofficeAsset.Asset.cafeImage.image)
P2: CofficeAsset.Asset.cafeImage.swiftUIImage 로 바꿔도 되는거죠?

2023-07-09 11:55 UTC, applebuddy approved these changes
고생 많으셨습니다!~

2023-07-09 11:56 UTC, merged