[Feat]/#133 카페 검색 시, waypoint 및 place api 호출 구현 및 역기반 이동
YAPP-Github/Coffice-iOS pull request #138
Opened 2023-07-11 07:44 UTC by NewHooon

## ☕️ PR 요약

- 카페 검색 시, waypoint 및 place api 호출 구현
- 역기반 이동

// TODO: 연관검색어 Cell 클릭 시, 해당 장소로 이동

## 📸 ScreenShot

![Simulator Screen Recording - iPhone 12 mini - 2023-07-11 at 16 40 07](https://github.com/YAPP-Github/Coffice-iOS/assets/108966759/a52cebf1-fe84-4891-8d67-f660d1c23277)
첨부해주세요.

#### Linked Issue

close #133

2023-07-11 09:02 UTC, Neph3779 requested changes
코멘트 확인 부탁드립니다~!

2023-07-11 09:02 UTC, Neph3779 commented on Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
> +          state.cafeMarkerList = searchResponse.cafes
마커 목록과 카페 목록에 같은 값이 들어가는 이유가 있나요?
그렇다면 왜 두개의 변수를 사용한건지 궁금합니다

2023-07-11 09:02 UTC, Neph3779 commented on Projects/Coffice/Sources/App/Main/Search/CafeSearchCore.swift
> +    case fetchWaypoints(String)
이곳 외에도 튜플에 라벨 안붙어있는 부분 정말 명확한 경우 제외하고 라벨 전부 붙여주시는게 좋을 것 같습니다.

2023-07-11 09:04 UTC, NewHooon commented on Projects/Coffice/Sources/App/Main/Search/CafeSearchCore.swift
> +    case requestWaypointSearchPlace(WayPoint)
맞습니다~!
작성해주신 방법이 훨씬 명확하네요 네이밍 수정하겠습니다.

2023-07-11 09:06 UTC, NewHooon commented on Projects/Coffice/Sources/App/Main/Search/CafeSearchCore.swift
> +                waypoint.name == state.searchText + waypoint.name.suffix(1) {
넵 반영하겠습니다~

2023-07-11 09:12 UTC, NewHooon commented on Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
> +          state.cafeMarkerList = searchResponse.cafes
두 역할이 비슷하나, 용어적 차이가 있어서 나눈 것 같습니다.
NaverMapView에서 cafeMarkerList를 마커라고 명확히 정의내려 사용하고 있다는 느낌이 들어서,
검색결과로 출력된 cafe목록들은 cafeList로 구분했던 것 같습니다. [사실, 결과는 동일하다는 생각이 듭니다]

2023-07-11 09:17 UTC, NewHooon commented on Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
> +          state.isMovingToCurrentPosition = true
"사용자의 현위치가 아닌  현 시점으로 카메라가  이동합니다" `isMovingToCurrentPosition`을 트리거 하여,
`CurrentCameraPosition` -> `NaverMapView CameraPosition`을 동기화 하는 로직을 확인하였고, 
따라서, 카페 검색 완료 시, 특정 카페로 CurrentCameraPosition을  동기화 시키는 과정이 필요하여 사용하였습니다.

2023-07-11 09:19 UTC, NewHooon commented on Projects/Coffice/Sources/App/Entities/WayPoint.swift
> +struct WayPoint: Equatable, Hashable {
반영하겠습니다

2023-07-11 09:27 UTC, NewHooon commented on Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
> +          state.isMovingToCurrentPosition = true
음 isMovingToCurrentPosition 명칭을 isMovingToCurrentCameraPosition으로 수정하면 적합할 것 같습니다~!!

2023-07-11 09:31 UTC, NewHooon commented on Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
> +          state.cafeMarkerList = searchResponse.cafes
cafeMarkerList 대신에, cafeList로 통일해도 좋을 것 같습니다~!

2023-07-11 09:33 UTC, NewHooon commented on Projects/Coffice/Sources/App/Main/Search/CafeSearchCore.swift
> +      /// 검색어가 "역"에 해당하는지, 카페목록이 존재하는지 판단
넵 네이밍 부분 더욱 신경써보겠습니다~

2023-07-11 09:36 UTC, NewHooon commented on Projects/Coffice/Sources/App/Main/Search/CafeSearchCore.swift
> +    var timingCheckFlag = false
맞습니다.. 이 부분 수정했습니다~

2023-07-11 09:36 UTC, NewHooon commented on Projects/Coffice/Sources/App/Main/Search/CafeSearchCore.swift
> +    // MARK: quickSearch
넵 반영하겠습니다

2023-07-11 09:36 UTC, NewHooon commented on Projects/Coffice/Sources/App/Main/Search/CafeSearchCore.swift
> +    case fetchWaypoints(String)
확인해서 반영하겠습니다~~!!

2023-07-11 09:38 UTC, Neph3779 commented on Projects/Coffice/Sources/App/Main/Search/CafeSearchCore.swift
> +      /// 검색어가 "역"에 해당하는지, 카페목록이 존재하는지 판단
단순 네이밍 외에도 이번 PR에는 로직의 간결성이 조금 더 필요해보입니다

2023-07-11 09:39 UTC, NewHooon commented on Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
> +          state.isMovingToCurrentPosition = true
엇 "현시점" -> "변경해야할 시점"  으로 명명하겠습니다. [ 카페 검색결과에서 받아온 특정 카페로의 현시점 이동이 적합한 것 같습니다]

2023-07-11 09:41 UTC, applebuddy reviewed
수고 많으셨어요. 
의견 확인 부탁드립니다.

2023-07-11 09:41 UTC, applebuddy commented on Projects/Coffice/Sources/App/Main/Search/CafeSearchCore.swift
> +          /// debounce로 연관검색어목록을 불러오는 것보다, 검색어 submit이 더 빠르게 진행된 경우
Q. /// 로 주석을 사용하신 목적이 있으신가요?

2023-07-11 09:41 UTC, applebuddy commented on Projects/Coffice/Sources/App/Main/Search/CafeSearchCore.swift
> +          }
Q. switch case 방식이 분기처리하기에 더 보기 좋아서 이렇게 사용하신 건가요?

2023-07-11 09:41 UTC, applebuddy commented on Projects/Coffice/Sources/App/Main/Search/NaverMapView.swift
> +          //지도 cameraPosition -> viewStore CurrentCameraPosition 동기화 작업
P2: 통일성 있게 // 뒤에 공백 한칸 두는게 좋을 것 같아요.

2023-07-11 09:42 UTC, NewHooon commented on Projects/Coffice/Sources/App/Main/Search/CafeSearchCore.swift
> +          }
넵 보기에 명확하다고 생각했습니다~!

2023-07-11 09:44 UTC, Neph3779 commented on Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
> +          state.isMovingToCurrentPosition = true
그럼 "카메라 포지션"으로 이동하는게 아니라
"받아온 카페"로 카메라가 이동해야되는거 아닌가요?
네이밍이 isMovingToCameraPosition이면 안될 것 같아요

2023-07-11 09:45 UTC, applebuddy commented on Projects/Coffice/Sources/App/Main/Search/CafeSearchCore.swift
> +        let isSubmitfasterThanDebounce = state.isSubmitfasterThanDebounce
+ Debounce를 대상으로하는게 아닌, 어떤 debounce가 적용되는 로직을 대상으로 이름 붙이는게 더 좋다는 생각이 들었습니다.

2023-07-11 09:47 UTC, applebuddy commented on Projects/Coffice/Sources/App/Main/Search/CafeSearchCore.swift
> +          .debounce(id: CancelID(), for: 0.2, scheduler: DispatchQueue.main)
P2: debounce에 대한 cancel id의 이름이 너무 포괄적인 것 같아요. 어떤 이벤트에 대한 cancelID인지 이름을 구체적으로 만들면 좋을 것 같습니다.

2023-07-11 09:57 UTC, NewHooon commented on Projects/Coffice/Sources/App/Main/Search/NaverMapView.swift
> +          //지도 cameraPosition -> viewStore CurrentCameraPosition 동기화 작업
넵 반영하겠습니다~

2023-07-11 09:58 UTC, NewHooon commented on Projects/Coffice/Sources/App/Main/Search/CafeSearchCore.swift
> +          .debounce(id: CancelID(), for: 0.2, scheduler: DispatchQueue.main)
맞습니다~! 목적과 용도에 맞게 네이밍 다듬겠습니다

2023-07-11 10:01 UTC, NewHooon commented on Projects/Coffice/Sources/App/Main/Search/CafeSearchCore.swift
> +          /// debounce로 연관검색어목록을 불러오는 것보다, 검색어 submit이 더 빠르게 진행된 경우
통상 변수명이나, 상수, 클래스, 함수, 등 설명이 필요한 곳에 사용한다고 알고 있었는데, 
편의대로 사용했던 것 같습니다.. 주석 제거하겠습니다~

2023-07-11 15:00 UTC, Neph3779 requested changes
코멘트 확인 부탁드려요~!

2023-07-11 15:00 UTC, Neph3779 commented on Projects/Coffice/Sources/App/Main/Search/CafeSearchCore.swift
> +        state.isSubmitFasterThanFetchResponse = false
isSubmitFasterThanFetchResponse가 정말 필요한가요?
그냥 fetch하던 중이면 이 fetch를 cancel하면 되지 않나요? (현재 네트워크 cancel 작업이 구현 안되어있으니, 그냥 response를 무시하면 될 것 같아요)

`시험지에 10이라는 숫자를 쓰다`
와
`30번 문제를 풀어 얻은 답인 10을 시험지에 쓰다`
랑은 서로 전달하는 의미가 다른데 동작은 같죠..

`isSubmitFasterThanFetchResponse`이라는 변수명은 
전자의 경우처럼 써있는 느낌입니다
왜 이 플래그가 필요한지 변수명에서 알 수 있으면 좋겠어요

지금도 충분히 발전된 변수명이지만
개선된 것과 approve하기에 충분한건 다르다 생각해서 코멘트 남깁니다..

2023-07-11 15:07 UTC, NewHooon commented on Projects/Coffice/Sources/App/Main/Search/CafeSearchCore.swift
> +        state.isSubmitFasterThanFetchResponse = false
"그냥 fetch하던 중이면 이 fetch를 cancel하면" -> 지하철 검색플로우 부분 때문에 문제가 발생하였습니다🥲
검색플로우에서, 유저가 타이핑 하는 도중에 [지하철, 카페] 데이터가 넘어오는데, 해당 데이터가 넘어오기전에 유저가 빠르게 검색을 진행한다면, [지하철, 카페] 데이터를 받아올 수 없고 -> 유저가 입력한 키워드가 지하철이라면 검색어가 지하철에 해당하는지 판단할 수가 없기에, Timing 이슈를 방지하고자 만든 플래그였습니다..! 조금 더 고민해보겠습니다~!

2023-07-11 16:08 UTC, applebuddy commented on Projects/Coffice/Sources/App/Main/Search/CafeSearchCore.swift
> +        state.isSubmitFasterThanFetchResponse = false
개발자가 처음 이 코드를 봤을때, isSubmitFasterThanFetchResponse 라는 이름을 보면, 아 이게 이 시점이구나 는 아는데, 그래서 무슨 이 값이 true 면 무슨 로직을 타는건지 다른 로직을 따로 봐야하거든요.

1) 그래서 음 네이밍이 참 어렵지만, 꼭 필요하다면, needToRetry~~~~ 식으로 이름을 정하면 최소한 이 값에 따라 어떤 비즈니스 로직이 수행될 지 알수있지않나 생각해요.
2) 그리고, 지금 로직이 마냥 단순한건 아니에요. 정 설명이 필요할것 같을때는 이럴때 flag 멤버에 /// 를 사용해서 quick help 주석을 달아두는건 생각해볼 수 있다고 생각해요.

2023-07-11 16:12 UTC, applebuddy commented on Projects/Coffice/Sources/App/Main/Search/CafeSearchCore.swift
> +              return .send(.requestSearchPlacesByWaypoint(waypoint: waypoint))
너무 복잡하게 생각하시는것 같은데, 위 조건들을 설명하는 상수를 그냥 위에 몇개 두고, 그거로 체크를하라는 말로 이해했어요. 
그렇게 하면 이 로직을 처음 볼때 더 쉽게 이해할 수 있을 것 같아요.

2023-07-12 08:57 UTC, Neph3779 reviewed
코멘트 확인 부탁드립니다~

2023-07-12 08:57 UTC, Neph3779 commented on Projects/Coffice/Sources/App/Main/Search/CafeSearchCore.swift
> +            await send(.retryFetchPlacesAndWaypointsResponse(places, waypoints, searchText: searchText))
일반적으로 "Response"라는 suffix가 붙으면
어떤 네트워크 통신의 응답값이 도착했을때 호출하는 action인데
이건 fetch를 요청하는건지, 응답값을 받아 처리하는건지 잘 모르겠어요

2023-07-12 08:57 UTC, Neph3779 commented on Projects/Coffice/Sources/App/Main/Search/CafeSearchCore.swift
> +            || "\(state.searchText)역" == waypoint.name
이렇게 지역변수에 놓지 말고 state에 연산 프로퍼티로 빼는게 좋을 것 같아요
가독성도 개선하고 해당 로직이 재활용될 수 있도록요

2023-07-12 08:57 UTC, Neph3779 commented on Projects/Coffice/Sources/App/Main/Search/CafeSearchCore.swift
> +            await send(.retryFetchPlacesAndWaypointsResponse(places, waypoints, searchText: searchText))
네이밍이 너무 어렵다면
그건 로직 분리가 필요한데, 안되었다는 증거이기도 합니다.
여러개의 동작을 하나의 단어로 설명할 수 없으니까 당연히 네이밍이 어려울 수 밖에 없습니다..

조금 더 개선해야 할 것 같습니다.
1년 뒤에 코드를 보고 이해하려면 
알고리즘 문제 정답 코드를 보듯 분석하는 시간을 가져야 할 것 같아요.. 🥲

2023-07-12 13:35 UTC, Neph3779 approved these changes
고생많으셨습니다!!!

2023-07-12 13:39 UTC, merged