Feature/#180 로그인 플로우 및 닉네임 검사 제작
YAPP-Github/Coffice-iOS pull request #189
Opened 2023-07-16 15:15 UTC by Neph3779

## ☕️ PR 요약

- 약관 동의를 제외한 로그인 플로우를 제작하였습니다
  - 앱을 처음 연 유저라면 (지웠다 깐 경우 포함)
  기존 키체인에 저장되어있는 토큰을 지웠습니다 (재설치시했음에도 키체인 토큰 남아있음으로 인한 자동 로그인 방지)
- 닉네임 validation api 연결
  - 정규식 활용해 특수문자를 아예 입력하지 못하게 하려 했으나 생각보다 복잡도가 높은 일이라 보류했습니다. 
  - 현재는 닉네임 검사를 서버에 의존하는중

## 기타 수정사항
- Design system의 red 색상변경 반영
- Coffice Logo 교체

#### Linked Issue

close #180

2023-07-16 17:50 UTC, applebuddy requested changes
카카오 로그인, 비회원 로그인 등 잘 동작하는 것 확인했습니다. 고생하셨습니다.
코멘트 확인 부탁드려요.

2023-07-16 17:50 UTC, applebuddy commented on Projects/Coffice/Sources/App/AppCoordinatorCore.swift
> +      if isAlreadyLoginned {
P2: logined 가 맞는것 같아요. 오타 수정 부탁드려요.

2023-07-16 17:50 UTC, applebuddy commented on Projects/Coffice/Sources/App/Login/LoginView.swift
>          }
P2: 그냥 customNavigationBar 관련 코드를 제거하는 것 어떨까요?

2023-07-16 17:50 UTC, applebuddy commented on Projects/Coffice/Sources/App/Main/MyPage/EditProfile/EditProfileView.swift
> +        }
P1: Reducer 내에서 이전 화면 복귀 시 탭바를 보이도록 하는 로직이 있어서 제거해도 될 것 같습니다. 그리고 이것 때문에 오류 로그가 발생하고 있어서 확인 부탁드려요~

```swift
      case .dismissButtonTapped:
        return .concatenate(
          EffectTask(value: .showTabBar),
          EffectTask(value: .popView)
        )
```

2023-07-16 23:01 UTC, Neph3779 commented on Projects/Coffice/Sources/App/AppCoordinatorCore.swift
> +      if isAlreadyLoginned {
문법을 찾아보니 loggedIn이 맞다고 하네요
loggedIn으로 수정하겠습니다!

2023-07-16 23:03 UTC, Neph3779 commented on Projects/Coffice/Sources/App/Login/LoginView.swift
>          }
커스텀 탭바가 없을때 상단 인셋 문제가 생긴다고 했던 것 같아서 놔뒀었는데
일단 지우고 문제 발생시 해당지점 수정하겠습니다!

2023-07-16 23:06 UTC, Neph3779 commented on Projects/Coffice/Sources/App/Main/MyPage/EditProfile/EditProfileView.swift
> +        }
dismiss랑 confirmButtonTapped에 모두 showTabBar 로직을 넣어놔서 해당 부분 지워도 문제 없네요!
지웠습니다~

2023-07-17 01:01 UTC, applebuddy approved these changes
LGTM

2023-07-17 02:30 UTC, applebuddy commented on Projects/Coffice/Sources/App/Login/LoginView.swift
>          }
그부분은 생각 못하고 남겼었네요~ 넵 neph님 판단대로 가시면 될 것 같습니다!

2023-07-17 04:12 UTC, merged