Feature/#197 로그아웃, 회원탈퇴 기능 연결
YAPP-Github/Coffice-iOS pull request #198
Opened 2023-07-18 14:40 UTC by Neph3779

## ☕️ PR 요약
- 로그아웃과 탈퇴 로직을 제작했습니다.
- 마이페이지의 카카오 로고가 채워진 버전이 필요해 이미지를 추가해 수정했습니다.

#### Linked Issue

close #197

2023-07-18 17:41 UTC, applebuddy requested changes
수고하셨습니다. onDisappear 관련 로직 제거도 잘된것 같아요.
다른부분은 의견 없으나, 회원탈퇴 등 하고 로그인페이지 진입 시, 둘러보기 등의 버튼이 먹통되는 문제가 있어서 관련 코멘트 달았습니다. 확인 부탁드립니다.

2023-07-18 17:41 UTC, applebuddy commented on Projects/Coffice/Sources/App/AppCoordinatorCore.swift
> +
그 외, AppCoordinator의 화면 관리 방식 고민이 필요해보이는데요. 

로그인 페이지에서 추가적인 네비게이션 전환 플로우가 존재하지 않는다면, LoginCoordinator를 제거하고 MainView 위에 로그인뷰 Modal(fullscreenCover)를 띄우면 어떨까 하는 생각이 들어요. LoginCoordinator를 만든 이유가 로그인 화면에서 회원가입등으로 네비게이션 전환 로직이 있을 것을 염두하고 구성했던건데 그게 불필요하다면, 의미가 없어서요. @NewHooon 

그러면 아마도 지금 Main 쪽 route 액션 에러 로그도 해결하기 쉬워질것 같아요~

2023-07-19 05:30 UTC, Neph3779 commented on Projects/Coffice/Sources/App/AppCoordinatorCore.swift
> +
문제상황 공유 감사합니다~!

2023-07-19 12:46 UTC, applebuddy approved these changes
LGTM

2023-07-20 03:23 UTC, merged