[UI] #70 card view redesign
YAPP-Github/Coffice-iOS pull request #76
Opened 2023-06-29 07:23 UTC by NewHooon

## ☕️ PR 요약

카드뷰를 디자인에 맞춰 변경하였습니다

- [ ] 디자인 변경
- [ ] 기기별 cardView 위치 고정[ iPhone 14 Pro, iPhone SE에서 확인]

## 📸 ScreenShot
<img src = "https://github.com/YAPP-Github/Coffice-iOS/assets/108966759/29c6539d-9544-4d2c-98e7-f730d954d165" width="200">

#### Linked Issue

close #70

2023-06-29 08:17 UTC, Neph3779 requested changes
코멘트 확인 부탁드립니다~!

2023-06-29 08:17 UTC, Neph3779 commented on Projects/Coffice/Sources/App/Main/Search/CafeCardView.swift
> +                  .frame(width: 124, height: 112)
요 frame 사이즈는 어디서 가져오신건가요? 
피그마상에서는 width 106.33, height 106으로 나와있어서요~

2023-06-29 08:17 UTC, Neph3779 commented on Projects/Coffice/Sources/App/Main/Search/CafeCardView.swift
> +                  .frame(width: 124, height: 112)
\+ 단순 수치만 가지고 디자인을 반영하면 안될 것 같아요
<img width="1363" alt="image" src="https://github.com/YAPP-Github/Coffice-iOS/assets/67148595/6e1ab63e-7c78-494a-961e-32d928b854e6">
피그마 캡쳐화면 우측에 보이듯
디자이너가 오토레이아웃을 사용해 뷰를 제작해주었습니다
하나의 카드안에 세개의 이미지가 담기도록 제작해야할 것 같아요

2023-06-29 08:17 UTC, Neph3779 commented on Projects/Coffice/Sources/App/Main/Search/CafeCardView.swift
> +          }
텍스트 색상 반영이 안된것 같아요~

2023-06-29 08:17 UTC, Neph3779 commented on Projects/Coffice/Sources/App/TabBarView.swift
> +          }
PreferenceKey 관련 코드 의도랑 동작 설명해주실 수 있으신가요?
TCA 문법으로는 해결이 안되는건지도 궁금합니다~

2023-06-29 08:29 UTC, NewHooon commented on Projects/Coffice/Sources/App/Main/Search/CafeCardView.swift
> +                  .frame(width: 124, height: 112)
피그마에 요 부분을 참고해서 제작했었는데 이제보니, list 뷰랑 card 뷰에서 레이아웃이 약간다르네요..? 
디자이너 코멘트 남겨주신 부분 참고해서 반영하겠습니다
<img width="681" alt="image" src="https://github.com/YAPP-Github/Coffice-iOS/assets/108966759/52401743-c4ce-4057-82dc-3799209ce4f9">

2023-06-29 08:30 UTC, NewHooon commented on Projects/Coffice/Sources/App/Main/Search/CafeCardView.swift
> +      .shadow(color: .gray, radius: 2, x: 0, y: 0)
이 부분은 제가 제대로 확인을 못했던 것 같습니다..!  
blur와 radius 이 부분도 올려주신 레퍼런스 링크 참고해서 확인하겠습니다~

2023-06-29 08:31 UTC, NewHooon commented on Projects/Coffice/Sources/App/Main/Search/CafeCardView.swift
> +          }
놓쳤네요..! 반영하겠습니다~

2023-06-29 08:38 UTC, NewHooon commented on Projects/Coffice/Sources/App/TabBarView.swift
> +          }
(1) Color.clear.preference(key: TabBarPreferenceKey.self, value: proxy.size): 
TabBarView의 size를 전달,
(2) .onPreferenceChange(TabBarPreferenceKey.self) { size in TabBarPreferenceKey.defaultValue = size } 
size 수신, 값 저장

이미 TabBarView에는 TabBarStore가 관리를 하고 있는 상황이고, 실제 CardView가 위치한 곳은 CafeMapView의 CafeMapCore 가 관리하고 있는 상태라, 서로 다른 두 스토어간 데이터 전달이 어렵다고 생각합니다
<img width="322" alt="image" src="https://github.com/YAPP-Github/Coffice-iOS/assets/108966759/976021d8-9b50-42cb-9c3f-81495ab00c35">

2023-06-29 08:44 UTC, Neph3779 commented on Projects/Coffice/Sources/App/Main/Search/CafeCardView.swift
> +      .shadow(color: .gray, radius: 2, x: 0, y: 0)
shadow가 확인하기 참 어려워서 반영할때 특별히 조심하고 있어요~

2023-06-29 08:44 UTC, Neph3779 commented on Projects/Coffice/Sources/App/Main/Search/CafeCardView.swift
> +                  .frame(width: 124, height: 112)
디자이너 답변 오면 다시 반영 후 리뷰하겠습니다~!

2023-06-29 09:04 UTC, applebuddy reviewed
공백 하나 확인 부탁드립니다~

2023-06-29 09:04 UTC, applebuddy commented on Projects/Coffice/Sources/App/PreferenceKeys/TabBarPreferenceKey.swift
> +  static func reduce(value: inout CGSize, nextValue: () -> CGSize ) {
끝에 ) 앞 공백 확인해주세요

2023-06-29 09:05 UTC, applebuddy commented on Projects/Coffice/Sources/App/TabBarView.swift
> +          }
사이즈를 전달한다면, TabBarSizePreferenceKey 처럼 사이즈 값에 관련된 것임을 알려주면 어떨까요

2023-06-29 09:07 UTC, NewHooon commented on Projects/Coffice/Sources/App/PreferenceKeys/TabBarPreferenceKey.swift
> +  static func reduce(value: inout CGSize, nextValue: () -> CGSize ) {
넵 확인했습니다~

2023-06-29 09:12 UTC, NewHooon commented on Projects/Coffice/Sources/App/TabBarView.swift
> +          }
지금보다, 변수명에서 목적이 명확하게 느껴지는 네이밍이라고 생각합니다~

2023-06-30 07:34 UTC, Neph3779 approved these changes
고생하셨습니다~!

2023-06-30 07:35 UTC, merged