[Feature] #77 cafe list view
YAPP-Github/Coffice-iOS pull request #86
Opened 2023-07-02 12:29 UTC by NewHooon

## ☕️ PR 요약

- CafeListSearchView 구현,
- 인수인계[Filter, bottomSheet]
- 추후, 무한스크롤 구현 예정

## 📸 ScreenShot

<img src = "https://github.com/YAPP-Github/Coffice-iOS/assets/108966759/89e6ef3b-5394-4009-b2bd-1b4df994c756" width = "200">

#### Linked Issue

close #77

2023-07-02 13:21 UTC, Neph3779 requested changes
고생하셨습니다! 코멘트 확인 부탁드려요~

2023-07-02 13:21 UTC, Neph3779 commented on Projects/Coffice/Sources/App/Main/Search/CafeCardView.swift
> +    }
cardView이면 위쪽 cornerRadius, shadow 설정등이 필요한것 같네요
cardView라는 네이밍이 혼란스러울 수 있을 것 같습니다! type명의 수정 혹은 cardView라는 변수명 수정이 필요해보여요!

2023-07-02 13:21 UTC, Neph3779 commented on Projects/Coffice/Sources/App/Main/Search/CafeCardView.swift
> +          Image(uiImage: CofficeAsset.Asset.bookmarkLine40px.image)
```suggestion
          CofficeAsset.Asset.bookmarkLine40px.swiftUIImage
```

2023-07-02 13:21 UTC, Neph3779 commented on Projects/Coffice/Sources/App/Main/Search/CafeSearchListCore.swift
> +        if state.pagenationRange ~= itemIdx || itemIdx/state.pageSize <= state.pageNumber {
1. idx라는 c언어식 변수명 줄이기는 지양하면 좋을 것 같아요
2. 수식을 변수로 만들어서 어떤 의도를 가진 수식인지 알 수 있으면 좋겠어요
  - 이것도 수식 자체도 의도가 명확해서 수식을 "해석"하는데 드는 시간이 없으면 좋겠습니다!

2023-07-02 13:21 UTC, Neph3779 commented on Projects/Coffice/Sources/App/Main/Search/CafeSearchListCore.swift
> +      case .detail: return "CofficeAsset.Asset.filterLine24px"
title에 어울리지 않는 값이 반환되고 있는 것 같아요

2023-07-02 13:21 UTC, Neph3779 commented on Projects/Coffice/Sources/App/Main/Search/CafeSearchListCore.swift
> +      }
size인데 Double로 관리하는 이유가 있을까요?
보통 view와 관련된 값은 CGFloat를 사용해서 여쭤봐요~

2023-07-02 13:21 UTC, Neph3779 commented on Projects/Coffice/Sources/App/Main/Search/CafeSearchListView.swift
> +            Image(asset: CofficeAsset.Asset.arrowLeftTopbarLine24px)
```suggestion
            CofficeAsset.Asset.arrowLeftTopbarLine24px.swiftUIImage
```

2023-07-02 13:21 UTC, Neph3779 commented on Projects/Coffice/Sources/App/Main/Search/CafeSearchListView.swift
> +          Image(asset: CofficeAsset.Asset.mapLine24px)
```suggestion
          CofficeAsset.Asset.mapLine24px.swiftUIImage
```

2023-07-02 13:21 UTC, Neph3779 commented on Projects/Coffice/Sources/App/Main/Search/FilterBottomSheetView.swift
> +              withAnimation { isApearSheet = true }
0.000001 과 같은 숫자가 들어간 이유가 뭔가요?
동작을 위해서 필요한 숫자라고는 생각되지만 바람직한 코드는 아닌 것 같습니다
변수명 혹은 number 관련 자료형에서 기본 제공하는 property들을 활용해보면 더 좋을 것 같아요

2023-07-02 13:21 UTC, Neph3779 commented on Projects/Coffice/Sources/App/Main/Search/FilterSheetCore.swift
> +    }
```suggestion
    return currentTappedState ? CofficeAsset.Colors.grayScale9 : CofficeAsset.Colors.grayScale7
```

2023-07-02 13:21 UTC, Neph3779 commented on Projects/Coffice/Sources/App/Main/Search/FilterSheetCore.swift
> +  }
```suggestion
  return currentTappedState ? CofficeAsset.Colors.grayScale9 : CofficeAsset.Colors.grayScale1
```

2023-07-02 13:21 UTC, Neph3779 commented on Projects/Coffice/Sources/App/Main/Search/FilterSheetCore.swift
> +  // TODO:
주석 작성 안된부분 작성 or 삭제 부탁드려요~

2023-07-02 13:34 UTC, NewHooon commented on Projects/Coffice/Sources/App/Main/Search/FilterBottomSheetView.swift
> +              withAnimation { isApearSheet = true }
delayTime 정도 변수명이면 적합할 것 같네요~!

2023-07-02 13:35 UTC, NewHooon commented on Projects/Coffice/Sources/App/Main/Search/CafeSearchListCore.swift
> +      }
이 부분은 제가 명확하게 파악하지 못한 것 같습니다..!

2023-07-02 13:36 UTC, NewHooon commented on Projects/Coffice/Sources/App/Main/Search/CafeSearchListCore.swift
> +      case .detail: return "CofficeAsset.Asset.filterLine24px"
확인했습니다~

2023-07-02 13:37 UTC, applebuddy requested changes
컨벤션 위주로 리뷰 드렸어요. 확인 부탁드립니다. 🙏🏻

2023-07-02 13:37 UTC, applebuddy commented on Projects/Coffice/Sources/App/Main/MainCoordinatorCore.swift
> +          return .none
아래 case 들은 한줄 여백이 있는데, 위에는 여백이 없어서 맞춰주면 좋을 것 같아요. 🤔

2023-07-02 13:37 UTC, applebuddy commented on Projects/Coffice/Sources/App/Main/Search/CafeCardView.swift
> +  enum ViewType {
여기 한 줄 띄는게 좋을 것 같아요.

2023-07-02 13:37 UTC, applebuddy commented on Projects/Coffice/Sources/App/Main/Search/CafeSearchListCore.swift
> +    var data: [SearchPlaceResponseDTO] = []
배열타입이니, data보다는 datas로 하는게 좋을 것 같아요. (data도 의미가 너무 큰 것 같긴해요.)

2023-07-02 13:37 UTC, applebuddy commented on Projects/Coffice/Sources/App/Main/Search/CafeSearchListCore.swift
> +    var pageNumber: Int = -1
음수값을 넣는게 조금 위험해보이는 느낌인데, 차라리 옵셔널타입으로 지정하면 너무 불편할까요?

2023-07-02 13:37 UTC, applebuddy commented on Projects/Coffice/Sources/App/Main/Search/CafeSearchListCore.swift
> +    case scrollAndloadData(Int)
카멜케이스 방식이라면 Andload -> AndLoad로 변경해주세요~

2023-07-02 13:37 UTC, applebuddy commented on Projects/Coffice/Sources/App/Main/Search/CafeSearchListCore.swift
> +      case .scrollAndloadData(let itemIdx):
idx보다는 index로 사용하는게 좋다고 생각해요. (이건 다수결 의견 받을게요. CC: @Neph3779 )

2023-07-02 13:37 UTC, applebuddy commented on Projects/Coffice/Sources/App/Main/Search/CafeSearchListCore.swift
> +        if state.pagenationRange ~= itemIdx || itemIdx/state.pageSize <= state.pageNumber {
연산자 사이는 가급전 전부 띄어주면 좋을 것 같아요.
```swift
if state.pagenationRange ~= itemIdx || (itemIdx / state.pageSize) <= state.pageNumber {
```

2023-07-02 13:37 UTC, applebuddy commented on Projects/Coffice/Sources/App/Main/Search/FilterSheetCore.swift
> +  // TODO:
TODO 주석 내용 없으면 지워주세요.

2023-07-02 13:37 UTC, applebuddy commented on Projects/Coffice/Sources/App/Main/Search/FilterSheetCore.swift
> +    case few
이런거 이름 나중에 다 통일해야겠네요 ㅠ (저는 다른 이름을 써서리 하하)

2023-07-02 13:37 UTC, NewHooon commented on Projects/Coffice/Sources/App/Main/Search/CafeSearchListCore.swift
> +        if state.pagenationRange ~= itemIdx || itemIdx/state.pageSize <= state.pageNumber {
무슨 말씀인지 파악했습니다~
" itemIdx/state.pageSize" 수식자체로는 같이 코드를 보는 사람이 이해하기 어려울 수 있다는 생각이 들었습니다

2023-07-02 13:39 UTC, applebuddy commented on Projects/Coffice/Sources/App/Main/Search/CafeSearchListCore.swift
> +        if state.pagenationRange ~= itemIdx || itemIdx/state.pageSize <= state.pageNumber {
idx 의견 저도 남겼는데 다수결에 따라 idx는 index로 바꾸는게 좋을것 같네요!

2023-07-02 13:54 UTC, applebuddy commented on Projects/Coffice/Sources/App/Main/Search/CafeSearchListView.swift
> +            Image(asset: CofficeAsset.Asset.arrowLeftTopbarLine24px)
엇 이런게 있었군여

2023-07-02 13:55 UTC, applebuddy commented on Projects/Coffice/Sources/App/Main/Search/FilterSheetCore.swift
> +    }
이건 근데 팀에서 정하기 나름인것같네요
그것보다도 전 currentTappedState 네임 의미가 헷갈려보여서 수정하면 좋겠다 싶어요

2023-07-02 14:24 UTC, NewHooon commented on Projects/Coffice/Sources/App/Main/Search/CafeSearchListCore.swift
> +    case scrollAndloadData(Int)
확인했습니다~!

2023-07-02 14:46 UTC, NewHooon commented on Projects/Coffice/Sources/App/Main/Search/CafeSearchListCore.swift
> +    var pageNumber: Int = -1
임의 설정값이였습니다~!

2023-07-02 14:46 UTC, NewHooon commented on Projects/Coffice/Sources/App/Main/Search/CafeSearchListCore.swift
> +    var data: [SearchPlaceResponseDTO] = []
넵 이 부분도 수정하겠습니다~

2023-07-02 14:47 UTC, NewHooon commented on Projects/Coffice/Sources/App/Main/Search/FilterSheetCore.swift
> +    case few
맞아요..!

2023-07-02 14:47 UTC, NewHooon commented on Projects/Coffice/Sources/App/Main/Search/CafeSearchListCore.swift
> +        if state.pagenationRange ~= itemIdx || itemIdx/state.pageSize <= state.pageNumber {
넵~!

2023-07-02 16:06 UTC, NewHooon commented on Projects/Coffice/Sources/App/Main/Search/CafeCardView.swift
> +          Image(uiImage: CofficeAsset.Asset.bookmarkLine40px.image)
[반영]

2023-07-02 16:09 UTC, NewHooon commented on Projects/Coffice/Sources/App/Main/Search/CafeSearchListCore.swift
> +        if state.pagenationRange ~= itemIdx || itemIdx/state.pageSize <= state.pageNumber {
[반영]

2023-07-02 16:12 UTC, NewHooon commented on Projects/Coffice/Sources/App/Main/Search/FilterSheetCore.swift
> +    }
아직 마땅한 naming을 찾지못해서, 현재 Tapped된 상태 정도로 두었습니다~

2023-07-02 16:14 UTC, NewHooon commented on Projects/Coffice/Sources/App/Main/MainCoordinatorCore.swift
> +          return .none
[반영]

2023-07-02 16:20 UTC, NewHooon commented on Projects/Coffice/Sources/App/Main/Search/CafeCardView.swift
> +  enum ViewType {
[반영]

2023-07-02 16:20 UTC, NewHooon commented on Projects/Coffice/Sources/App/Main/Search/CafeSearchListCore.swift
> +    var pageNumber: Int = -1
구체적인 사양 나오면 다시 수정해봐야할 것 같습니다~

2023-07-02 16:21 UTC, NewHooon commented on Projects/Coffice/Sources/App/Main/Search/CafeSearchListCore.swift
> +    case scrollAndloadData(Int)
[반영]

2023-07-02 16:21 UTC, NewHooon commented on Projects/Coffice/Sources/App/Main/Search/CafeSearchListCore.swift
> +      case .scrollAndloadData(let itemIdx):
[반영]

2023-07-02 16:21 UTC, NewHooon commented on Projects/Coffice/Sources/App/Main/Search/CafeSearchListCore.swift
> +        if state.pagenationRange ~= itemIdx || itemIdx/state.pageSize <= state.pageNumber {
[반영]

2023-07-02 16:26 UTC, applebuddy requested changes
추가적으로 리뷰 남겨두었습니다.(제가 이어서 작업할 코드인지라 🙏🏻) 확인 부탁드립니다.

2023-07-02 16:26 UTC, applebuddy commented on Projects/Coffice/Sources/App/Main/MainCoordinatorCore.swift
> +          return .none
P0 : 여기 ! 대신 옵셔널 체이닝 방식을 사용하면 문제 되는게 있나요?

2023-07-02 16:26 UTC, applebuddy commented on Projects/Coffice/Sources/App/Main/Search/CafeCardView.swift
> +            Text("월: 11:00 ~23:00")
임시 문자열이긴 하지만.... ~ 뒤에 공백 하나 있어야 하지 않나 해서 남겨요. (11:00 ~ 23:00)

2023-07-02 16:26 UTC, applebuddy commented on Projects/Coffice/Sources/App/Main/Search/CafeCardView.swift
> +
버튼 액션이 비어있는데 TODO를 남겨두면 좋을 것 같아요.

2023-07-02 16:26 UTC, applebuddy commented on Projects/Coffice/Sources/App/Main/Search/CafeSearchListCore.swift
> +      case .fetchData(let requestValue):
searchPlaces API를 요청하는 것을 알 수 있는 action명이 되는게 좋을 것 같아요. + dataResponse 도.... 어떤 데이터 응답을 처리하는 것 인지 한눈에 알 수가 없어요.
(fetchSearchPlacesData나 searchPlaces 라던가... 근데 fetchData는 그 자체가 뭔가를 반환할 것 같은 느낌이 드는데 의견들 듣고 싶어요. CC: @Neph3779 )

2023-07-02 16:26 UTC, applebuddy commented on Projects/Coffice/Sources/App/Main/Search/CafeSearchListView.swift
> +          } label: {
여기도 어떤 액션을 구현해야할지 TODO 적어주면 좋을 것 같습니다.

2023-07-02 16:26 UTC, applebuddy commented on Projects/Coffice/Sources/App/Main/Search/CafeSearchListView.swift
여기도 TODO 주석 확인 부탁드립니다. (협업관점에서 인수인계하는 코드인 만큼 중요하다고 생각합니다.)

2023-07-02 16:26 UTC, applebuddy commented on Projects/Coffice/Sources/App/Main/Search/CafeSearchListView.swift
> +    WithViewStore(store) { store in
WithViewStore의 후행클로져 parameter 이름이 store로 사용되고 있습니다. ViewStore 타입 아닌가요?

2023-07-02 16:26 UTC, applebuddy commented on Projects/Coffice/Sources/App/Main/Search/CafeSearchListView.swift
> +                           .stroke(Color(asset: CofficeAsset.Colors.grayScale4), lineWidth: 1)
파일 전체적으로 들여쓰기 간격이 안맞아요. 2칸 간격인지 확인해주세요.

2023-07-02 16:29 UTC, NewHooon commented on Projects/Coffice/Sources/App/Main/MainCoordinatorCore.swift
> +          return .none
엇 문제없습니다~! 수정하겠습니다

2023-07-02 16:29 UTC, NewHooon commented on Projects/Coffice/Sources/App/Main/Search/CafeCardView.swift
> +            Text("월: 11:00 ~23:00")
넵 반영하겠습니다

2023-07-02 16:33 UTC, NewHooon commented on Projects/Coffice/Sources/App/Main/Search/CafeSearchListView.swift
> +    WithViewStore(store) { store in
엇 맞습니다 수정하겠습니다

2023-07-03 00:58 UTC, NewHooon commented on Projects/Coffice/Sources/App/Main/Search/CafeSearchListCore.swift
> +    var data: [SearchPlaceResponseDTO] = []
data가 datum(하나의 자료)의 복수형으로, 이미 복수형인 것 같습니다~ 그래서
searchPlaceData, 정도로 명칭 변경하겠습니다

2023-07-03 02:47 UTC, applebuddy reviewed
몇개 수정사항이 보여서 남겨요. 이부분 수정되면 승인 하겠습니다.

2023-07-03 02:47 UTC, applebuddy commented on Projects/Coffice/Sources/App/Main/Search/CafeSearchListCell.swift
> +
한칸 공백 제거해주세요.

2023-07-03 02:47 UTC, applebuddy commented on Projects/Coffice/Sources/App/Main/Search/CafeSearchListCore.swift
> +    var searchPlaceData: [Cafe] = []
data -> datas 로 바꿔주세요. 배열같지 않은 이름이라서 혼동이 올 것 같아요. (CC: @Neph3779)
기본 컨벤션 참고하기로 한 kodeco 가이드라인에서도 그런 방식으로 사용하고 있습니다.
- reference : https://github.com/kodecocodes/swift-style-guide#type-inference

2023-07-03 02:53 UTC, NewHooon commented on Projects/Coffice/Sources/App/Main/Search/CafeSearchListCore.swift
> +    var searchPlaceData: [Cafe] = []
data가 datum의 복수형이라, 이미 복수형의 자료들을 data라고 하는 것 같습니다! 다른 명칭으로 바꿀까요~?

2023-07-03 03:34 UTC, applebuddy submitted a review, later dismissed
수고하셨습니다~!!
(하단 시트뷰에 필터 옵션 버튼 보이네요 ㅎㅎ)

2023-07-03 05:02 UTC, Neph3779 approved these changes
변경내용들 확인했습니다!
고생 많으셨습니다~!

2023-07-03 05:17 UTC, merged