[Feat] #93 cafe search view
YAPP-Github/Coffice-iOS pull request #98
Opened 2023-07-05 08:30 UTC by NewHooon

## ☕️ PR 요약

검색 뷰 UI 및 검색 기능을 구현하였습니다

## 📸 ScreenShot

![Simulator Screen Recording - iPhone 14 Pro - 2023-07-05 at 17 29 18](https://github.com/YAPP-Github/Coffice-iOS/assets/108966759/27267823-2672-4b94-9aac-297ffa32fdf1)

#### Linked Issue

close #93 #99

2023-07-05 10:16 UTC, applebuddy requested changes
수고하셨습니다. 리뷰 확인 부탁드립니다.

2023-07-05 10:16 UTC, applebuddy commented on Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
> +    var cafeList: [Cafe] = []
P2: cafeMarkers, cafes는 별로일까요? ~List보다는 ~s가 더 좋은 이름이라는 의견이 있어서 남깁니다. @Neph3779

2023-07-05 10:16 UTC, applebuddy commented on Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
> +          state.selectedCafe = cafeList.first!
P1: ! 가 꼭 필요한지 확인해주세요.

2023-07-05 10:16 UTC, applebuddy commented on Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
> +            longitude: state.selectedCafe!.longitude
P1: ! 가 꼭 필요한지 확인해주세요. !는 정말 없으면 큰일나는게 아니면 지양하면 좋겠다고 생각합니다.

2023-07-05 10:16 UTC, applebuddy commented on Projects/Coffice/Sources/App/Main/Search/CafeMapView.swift
> +                .background(.white)
P2: 색상이 white로 동일하게 적용 되더라도, grayscale1 같은 명칭이 있다면 규칙에 맞게 명시하는게 좋다고 생각합니다.

2023-07-05 10:16 UTC, applebuddy commented on Projects/Coffice/Sources/App/Main/Search/CafeMapView.swift
> +                CafeCardView(store: store, cafe: viewStore.state.selectedCafe!)
P1: !가 꼭 필요한지 확인해주세요.

2023-07-05 10:16 UTC, applebuddy commented on Projects/Coffice/Sources/App/Main/Search/CafeSearchCore.swift
> +        if state.searchText == "" {
P2: isEmpty가 더 보기 좋을 것 같아서 남겨요

2023-07-05 10:16 UTC, applebuddy commented on Projects/Coffice/Sources/App/Main/Search/CafeSearchCore.swift
> +      case .onApear:
P1: 철자 확인해주세요~ Appear

2023-07-05 10:16 UTC, applebuddy commented on Projects/Coffice/Sources/App/Main/Search/CafeSearchView.swift
> +  }
WithViewStore의 observe를 활용할 수 있겠네요

```swift
  var cafeSearchBodyView: some View {
    WithViewStore(store, observe: \.currentBodyType) { viewStore in
      switch viewStore.state {
      case .recentSearchListView:
        recentSearchListView

      case .searchResultEmptyView:
        searchResultEmptyView

      case .searchResultListView:
        searchResultListView
      }
    }
  }
```

2023-07-05 10:16 UTC, applebuddy commented on Projects/Coffice/Sources/App/Main/Search/CafeSearchView.swift
> +          ForEach(viewStore.cafeList, id: \.self) {_ in
P1: 클로져 parameter 앞 공백 확인해주세요.

2023-07-05 10:16 UTC, applebuddy commented on Projects/Coffice/Sources/App/Main/Search/CafeSearchListView.swift
> +              ForEach(0..<viewStore.cafeList.count, id: \.self) { index in
범위연산자 컨벤션이 궁금해서 kodeco 가이드 라인 찾아보니, 적어주신것처럼 붙여서 쓰고 있네요. > < + 같은건 앞뒤를 띄우는 것 같고... [참고](https://github.com/kodecocodes/swift-style-guide#control-flow)하세요~

2023-07-05 10:17 UTC, applebuddy commented on Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
> +    var cafeList: [Cafe] = []
근데 워낙 바뀌는 부분이 커서 (파일도 그렇고, 룰을 정한것도 아니니....) 변경하더라도 변경하기가 애매할것 같긴해요.

2023-07-05 10:20 UTC, Neph3779 commented on Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
> +    var cafeList: [Cafe] = []
저는 cafes에 한표 던집니다 ㅎㅎ
근데 크게 중요하진 않다고 생각해요

2023-07-05 10:55 UTC, NewHooon commented on Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
> +    var cafeList: [Cafe] = []
그럼 추후에 반영하겠습니다~

2023-07-05 10:56 UTC, NewHooon commented on Projects/Coffice/Sources/App/Main/Search/CafeSearchCore.swift
> +      case .onApear:
철자를 틀렸네요.. 조금 더 신경쓰도록하겠습니다~!

2023-07-05 10:57 UTC, NewHooon commented on Projects/Coffice/Sources/App/Main/Search/CafeSearchView.swift
> +  }
좋은 피드백 감사합니다~! 해당 부분 반영하도록 하겠습니다.

2023-07-05 10:58 UTC, NewHooon commented on Projects/Coffice/Sources/App/Main/Search/CafeSearchListView.swift
> +              ForEach(0..<viewStore.cafeList.count, id: \.self) { index in
연산자 사용 시, 언급해주신 kodeco 컨벤션 참고하면서 작성하겠습니다~!

2023-07-05 10:58 UTC, NewHooon commented on Projects/Coffice/Sources/App/Main/Search/CafeSearchCore.swift
> +        if state.searchText == "" {
맞습니다~! 해당 부분 반영하도록 하겠습니다.

2023-07-05 10:59 UTC, NewHooon commented on Projects/Coffice/Sources/App/Main/Search/CafeMapView.swift
> +                .background(.white)
확인했습니다~! 언급해주신대로 grayscale1로 설정하도록 하겠습니다

2023-07-05 11:00 UTC, NewHooon commented on Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
> +          state.selectedCafe = cafeList.first!
Forced unwrapping 방식 최대한 지양하도록 하겠습니다!

2023-07-05 11:09 UTC, Neph3779 requested changes
양이 많네요! 고생하셨습니다~! 
코멘트 확인 부탁드립니다~

2023-07-05 11:09 UTC, Neph3779 commented on Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
> +        state.displayViewType = .mainMapView
이 부분은 따로 action을 만들어서 이름을 붙여줘도 좋을 것 같아요
cleanUpPreviousResults 등으로요

2023-07-05 11:09 UTC, Neph3779 commented on Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
> +          }
이 부분도 메서드화(TCA에서는 action화가 더 맞을 것 같네요)가 필요해보여요~
어떤 동작을 하는건지 이름을 붙여주면 좋겠어요

2023-07-05 11:09 UTC, Neph3779 commented on Projects/Coffice/Sources/App/Main/Search/CafeSearchCore.swift
> +  }
위에서 만드신 ViewType을 재활용할 수는 없는걸까요?

2023-07-05 11:09 UTC, Neph3779 commented on Projects/Coffice/Sources/App/Main/Search/CafeSearchCore.swift
> +    var recentSearchKeyWordList: [SearchWordResponseDTO] = []
```suggestion
    var recentSearchKeywordList: [SearchWordResponseDTO] = []
```

2023-07-05 11:09 UTC, Neph3779 commented on Projects/Coffice/Sources/App/Main/Search/CafeSearchCore.swift
> +        }
index 기반이 아닌 item 기반의 코드가 되었으면 좋겠어요
제가 북마크 화면에서 택한 방식을 참고해주셔도 좋을 것 같아요
index를 통해 배열에 접근하는건 force unwrapping과 다를바 없는 행위라 생각하거든요

2023-07-05 11:09 UTC, Neph3779 commented on Projects/Network/Sources/DTOs/Responses/SearchWordResponseDTO.swift
> +public struct SearchWordResponseDTO: Decodable, Equatable {
Entity를 사용하면 이런식으로 DTO에 Domain 영역에서 사용하기 위한 protocol 채택을 하지 않아도 된답니다
Network Layer에 의존하지 않을 수 있는거죠!

2023-07-05 11:11 UTC, applebuddy commented on Projects/Coffice/Sources/App/Main/Search/CafeCardView.swift
> +                    .foregroundColor(Color(asset: CofficeAsset.Colors.grayScale9))
저도 이런방식으로 쓰도록 할게요

2023-07-05 11:14 UTC, applebuddy commented on Projects/Coffice/Sources/App/Main/Search/CafeSearchCore.swift
> +        }
indexing 관련해서 접근가능할때만 값을 추출하도록 safe: 첨자접근방식 적용해보면 어떨까싶어요. 현업에서도 자주쓰고있어요.
array[safe: 1] 식으로 사용하고 옵셔널 타입 반환

2023-07-05 11:15 UTC, applebuddy commented on Projects/Coffice/Sources/App/Main/Search/CafeSearchCore.swift
> +        }
~~~swift

public extension Array {
    public subscript (safe index: Int) -> Element? {
        return self.indices ~= index ? self[index] : nil
    }
}
~~~

2023-07-05 11:17 UTC, NewHooon commented on Projects/Coffice/Sources/App/Dependencies/SearchWordAPIClient.swift
> +  func fetchRecentSearchWords() async throws -> [SearchWordResponseDTO] {
넵~! Entity 따로만들어서 적용하겠습니다

2023-07-05 11:18 UTC, Neph3779 commented on Projects/Coffice/Sources/App/Main/Search/CafeSearchCore.swift
> +        }
@applebuddy 위 방식 현업에서 쓰실때 느끼신 장단점 말해주실 수 있으신가요?
궁금해서 여쭤봅니당 ㅎㅎ..
코드 자체는 옛날에 민소네님 블로그에서 본 적이 있던 것 같아요

2023-07-05 11:19 UTC, NewHooon commented on Projects/Coffice/Sources/App/Main/Search/CafeCardView.swift
> +                ForEach(1...10, id: \.self) { _ in
넵 이슈를 새로 파서 진행해보겠습니다~

2023-07-05 11:19 UTC, NewHooon commented on Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
> +    case resultMapView
좋은 의견인 것 같습니다~! 꼼꼼한 리뷰 감사드립니다

2023-07-05 11:20 UTC, NewHooon commented on Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
> +        state.displayViewType = .mainMapView
이 부분 확인해보겠습니다~!

2023-07-05 11:21 UTC, NewHooon commented on Projects/Coffice/Sources/App/Main/Search/CafeSearchCore.swift
> +  }
이 부분 확인해보겠습니다~!

2023-07-05 11:23 UTC, NewHooon commented on Projects/Coffice/Sources/App/Main/Search/CafeSearchCore.swift
> +        }
그러네요~! 이 부분 수정하겠습니다

2023-07-05 11:24 UTC, applebuddy commented on Projects/Coffice/Sources/App/Main/Search/CafeSearchCore.swift
> +        }
일단 바로 못벗겨서 불편할때가 있긴하지만 말씀주신대로 안전하게 인덱싱을 하기 위해 사용하는 정도 같아요~
(옵셔널바인딩도 코드가 길어지지만 안정성을 위해 사용하니..)

2023-07-05 11:24 UTC, NewHooon commented on Projects/Network/Sources/DTOs/Responses/SearchWordResponseDTO.swift
> +public struct SearchWordResponseDTO: Decodable, Equatable {
좋은 의견 감사드립니다~! 확인해서 entity로 변경하겠습니다!

2023-07-05 13:27 UTC, applebuddy commented on Projects/Coffice/Sources/App/Main/Search/CafeMapView.swift
> +                CafeCardView(store: store, cafe: viewStore.state.selectedCafe!)
+ viewStore.isSelectedCafe로 써도 될 것 같아요

2023-07-05 13:55 UTC, applebuddy commented on Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
> +        state.displayViewType = .mainMapView
reset / removeAll 같은 prefix도 괜찮을것 같다는 의견입니다.

2023-07-06 03:05 UTC, Neph3779 reviewed
코멘트 하나 확인 부탁드려요~

2023-07-06 03:05 UTC, Neph3779 commented on Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
> +    case resetResultsWhenSearchResultIsEmpty
action명 자체에 조건문을 건듯한 느낌이네요..
resetResults라는 action 하나만 두고 state를 검사해서 때에 맞는 처리를 해주는게 맞을 것 같아요

2023-07-06 03:25 UTC, NewHooon commented on Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
> +    case resetResultsWhenSearchResultIsEmpty
action을 하나로, state로 분기처리하는 것이 보일러플레이트 코드를 줄일 수 있는 것 같네요..!

2023-07-06 03:26 UTC, Neph3779 approved these changes
고생하셨습니다~!

2023-07-06 04:02 UTC, applebuddy approved these changes
고생하셨습니다~!

2023-07-06 04:03 UTC, merged